### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by sankarnadendla** [FasterXML/jackson-annotations#167]
We are getting this issue when we upgraded from org.codehaus.jackson  to com.fasterxml.jackson.core with 2.10.2 
java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonMerge
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.<clinit>(JacksonAnnotationIntrospector.java:50)
        at com.fasterxml.jackson.databind.ObjectMapper.<clinit>(ObjectMapper.java:341)
        at org.apache.avro.Schema.<clinit>(Schema.java:109)
        
Please help me in resolving this issue. TIA

**Comment by cowtowncoder** [comment]
You seem to have version incompatibility in your classpath. `JsonMerge` was added in 2.9, so somehow your `jackson-annotations` version is older than that.

**Comment by sankarnadendla** [comment]
Could I have some advice on how to remediate the incompatibility in my classpath. TIA

**Comment by cowtowncoder** [comment]
@sankarnadendla that is something you will need to figure out on your own. Make sure to use same minor version of all Jackson components.

Good luck!
