### ISSUE TITLE
Multiple Variable Declarations (Single Line)

### ISSUE THREAD

**Issue by ememisya** [FasterXML/jackson-annotations#209]
Would it be sensible to convert the default value to a String[] array rather than a String?

https://github.com/FasterXML/jackson-annotations/blob/1d1f1a594c7f0ce0d3e6a342537d4c70d4ca1ed5/src/main/java/com/fasterxml/jackson/annotation/JsonProperty.java#L66

Given the following scenario:  
  
```
  /**
   * Three fields at once with one name
   */
  @JsonProperty("name")
  private String one, two, three;
```
The following exception is thrown:  

**com.fasterxml.jackson.databind.exc.InvalidDefinitionException: 
Conflicting getter definitions for property "name": <class>**  

The above code compiles into the following:

```
  // access flags 0x2
  private Ljava/lang/String; one
  @Lcom/fasterxml/jackson/annotation/JsonProperty;(value="name")

  // access flags 0x2
  private Ljava/lang/String; two
  @Lcom/fasterxml/jackson/annotation/JsonProperty;(value="name")

  // access flags 0x2
  private Ljava/lang/String; three
  @Lcom/fasterxml/jackson/annotation/JsonProperty;(value="name")
  
```

If the following was possible:

```
  /**
   * Three fields at once with three names
   */
  @JsonProperty({"nameOne", "nameTwo", "nameThree"})
  private String one, two, three;
  
  /**
   * Single field
   */
  @JsonProperty("singleField")
  private String single;
```

One could check for the exception and try the next element in the array, which should always be sorted properly by the compiler to infer from source.

**Comment by ememisya** [comment]
I'm certain the field order is preserved for all JVM implementations for variable declarations owned by a single field declarator.  It would be the most efficient way of compiling them syntactically and all vendor implementations return them by the order of appearance in the bytecode file.  So the logic (if already mapped, and multiple values on annotation, use next) would work.

DVM is the exception however it does seem to sort getFields but not getDeclaredFields given the same context described above.  Although this **not** being guaranteed by a contract does make implementing my original suggestion a **bad idea** (it would work everywhere, but without a contractual guarantee).

That being said, one approach could be to still make it a String[] for backwards compatibility however require pairs of values where [n] is the desired property name and [n+1] is the variable declarator name which would make it compatible with both DVM and JVM as well as abide by the _The elements in the returned array are not sorted and are not in any particular order._ wording in the docs.  Given how rare field declarators with multiple variable declarators are in the wild I wouldn't say it would be unusual to require such pairing AND Jackson library would be more in line with JLS.

What do you think?

**Comment by cowtowncoder** [comment]
I don't think I have interest in pursuing this any further.

**Comment by ememisya** [comment]
> I don't think I have interest in pursuing this any further.

The laziest way forward would be to include some wording under the annotation forbidding the use of the annotation over multiple variable declarators.

**Comment by cowtowncoder** [comment]
I'd be happy to merge a PR for improved Javadoc description. I wouldn't necessary call it forbidding, but warning maybe.

**Comment by ememisya** [comment]
> I'd be happy to merge a PR for improved Javadoc description. I wouldn't necessary call it forbidding, but warning maybe.

According to the Java Language Specification with the introduction of JSR-175 a field may be annotated which has an array type for variables it declares.  An annotation applies to all variables as demonstrated on the following code:

```
package sample;

public class NewClass
{
  @JsonProperty(value = "{\"one\":\"oneNew\",\"two\":\"twoNew\",\"three\":\"threeNew\"}")
  String one, two, three;
}
```


Calling the following method:

``
NewClass test = objectMapper.readValue("{ \"one\": \"1\", \"two\": \"2\", \"three\": \"3\"}", NewClass.class);
``

Produces the following error:

> Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Multiple fields representing property "oneNew,twoNew,threeNew": sample.NewClass#one vs sample.NewClass#two
>  at [Source: {"one":"oneNew","two":"twoNew","three":"threeNew"}; line: 1, column: 1]
> 	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:305)
> 	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:268)
> 	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
> 	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
> 	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:476)
> 	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3899)
> 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3794)
> 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2842)
> 	at edu.vt.middleware.ws.duo.proxy.rest.UserController.main(UserController.java:36)
> Caused by: java.lang.IllegalArgumentException: Multiple fields representing property "{"one":"oneNew","two":"twoNew","three":"threeNew"}": sample.NewClass#one vs sample.NewClass#two
> 	at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getField(POJOPropertyBuilder.java:354)

The syntax is valid and there is no possible way it executes without an exception.

The value expression on the annotation cites the following:

_Defines name of the logical property, i.e. JSON object field name to use for the property. If value is empty String (which is the default), will try to use name of the field that is annotated. Note that there is no default name available for constructor arguments, meaning that Empty String is not a valid value for constructor arguments._

In the valid case above, there is no _object field name to use for the property_.  This should have been considered in the implementation.  Another solution to this could be that the JsonProperty annotation's _value_ is parsed as an expression (as attempted in the example above) and not a String representing a single variable name.

I will have to take some time and read the databind project to be able to come up with a PR for both that one and this one as I am fairly new to the Jackson project.

**Comment by ememisya** [comment]
I am certain there are people who would be happy to contribute the changes out there who can work faster and better than myself so perhaps closing the issue may not be the best path forward for the project.  
  
While I mentioned the lazy way forward would be a change in the documentation it still isn't the right way to deal with this issue to note, "does not fully conform to Java language specifications."  FasterXML is a very popular project and it deserves to have no obvious flaws.  
  
Thank you for your time and for having a look at this.

**Comment by cowtowncoder** [comment]
I don't consider this to be a flaw but rather consequence of the way Java annotations work.
To me the only thing to improve, possibly, would be to add a note in Javadocs; although given dozens of annotations types this may be impractical as well.
I also find it unlikely that this problem is hit by many users given that this is the first time I've heard about it.

**Comment by ememisya** [comment]
> But I am surprised that the same annotation is actually assigned to all declared Fields.
...
> I don't consider this to be a flaw but rather consequence of the way Java annotations work.

You are incorrect on that assessment.  Java Language Specification has a one to many association for field and variable declarators.  JsonProperty value expression does not accommodate that fact and incorrectly identifies it as a one to one association.

**Comment by ememisya** [comment]
As a result of our discussion I have created the following request: https://github.com/FasterXML/jackson-annotations/pull/210
